### ISSUE TITLE
upload_image method doesn't work on python 3.4

### ISSUE THREAD

**Issue by itshnegg** [cloudinary/pycloudinary#71]
upload_image() throws an exception 

> 'Request' object has no attribute 'has_data'

in python 3.4. Mehods urllib.request.Request.has_data and urllib.request.Request.get_data were deprecated in Python 3.3 and have been removed in Python 3.4

**Comment by fen-x** [comment]
Got same exception. I am using monkey patching to work around. Looking forward for official fix.

**Comment by roeeba** [comment]
`urllib2` was replaced with `urllib3` in this commit:
https://github.com/cloudinary/pycloudinary/commit/5e4fc9e46371f75dfa8acb578775da09ad06e075
